services:
  trpg-bot:
    image: local/trpg-bot:latest
    build:
      context: .
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    depends_on:
      mongo:
        condition: service_healthy
    profiles:
      - production
  mongo:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
    profiles:
      - production
      - local
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      mongo:
        condition: service_healthy
    profiles:
      - local
