name: terraform ci

on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        description: terraform command
        default: plan

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_VAR_DISCORD_BOT_TOKEN: ${{ secrets.TF_VAR_DISCORD_BOT_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Terraform Version
        working-directory: '.'
        run: |
          echo "TERRAFORM_VERSION=$(cat .tool-versions | grep terraform | awk '{print $2}')" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Plan
        if: ${{ github.event.inputs.command == 'plan' }}
        working-directory: '.'
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.command == 'apply' }}
        working-directory: '.'
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve
